[base]
package = ocean
env_name = puffer_poly_tm
policy_name = PolyTM
rnn_name = PolyTMLSTM

[vec]
num_envs = 16

[env]
cont_rew_div = 3.1362846391980597
cont_rew_mul = 4.815977986426888
correctness_reward = 36.41370764572932
incorrectness_penalty = 26.910471927081403
invalid_output_penalty = 3.7709404285799977

log_episodes = 10
log_interval = 100

max_steps = 43.59004970073508
move_head = 29.864283519685674

nen_halt_penalty = 3.3071637357622206

num_envs = 1024

num_result_heads=1
num_state_heads=1
num_work_heads=2

problem_size = 4

result_observation_window = 27.78953720016705
result_tape_size = 120

state_observation_window = 31.8190884641093
state_tape_size = 120

tape_alphabet = 10

write_rew_multiplier = 10.0

work_observation_window = 39.8463640355379
work_tape_size = 120
; max_a = 4
; max_i = 50
; max_u = 100

; cont_rew_div = 2.75
; cont_rew_mul = 5.5
; correctness_reward = 30
; incorrectness_penalty = 0.0
; invalid_output_penalty = 3

; log_episodes = 10
; log_interval = 100

; max_steps = 550
; move_head = 23

; nen_halt_penalty = 2.75

; num_envs = 1024

; num_result_heads = 1
; num_state_heads = 1
; num_work_heads = 3.5

; problem_size = 4

; result_observation_window = 20
; result_tape_size = 150

; state_observation_window = 20
; state_tape_size = 150

; tape_alphabet = 10

; write_rew_multiplier = 1.0

; work_observation_window = 20
; work_tape_size = 150
; max_a = 4
; max_i = 50
; max_u = 100


[train]
adam_beta1 = 0.6991889042451376
adam_beta2 = 0.9968459294078819
adam_eps = 2.867951737080607e-7

bptt_horizon = 64
checkpoint_interval = 200
clip_coef = 0.04675587982158977
ent_coef = 0.029421123595985962
gae_lambda = 0.9298515992833183
gamma = 0.9555672676863619
learning_rate = 0.03831943969808964
max_grad_norm = 1.924267982270226
max_minibatch_size = 32768
minibatch_size = 32768
prio_alpha = 0.8967194004562238
prio_beta0 = 0.5394172845661204
total_timesteps = 1262716120.395078

vf_clip_coef = 0.1
vf_coef = 1.3542915034708227
vtrace_c_clip = 0.26343176388780587
vtrace_rho_clip = 0.692687692067663

; adam_beta1 = 0.9
; adam_beta2 = 0.999
; adam_eps = 1e-8

; bptt_horizon = 64
; checkpoint_interval = 200
; clip_coef = 0.2
; ent_coef = 0.01000000000000001
; gae_lambda = 0.95
; gamma = 0.98
; learning_rate = 0.01000000000000001
; max_grad_norm = 1
; max_minibatch_size = 32768
; minibatch_size = 32768
; prio_alpha = 0.8499999999999999
; prio_beta0 = 0.8499999999999999
; total_timesteps = 1000000000

; vf_clip_coef = 0.20000000000000012
; vf_coef = 2
; vtrace_c_clip = 1
; vtrace_rho_clip = 1

[sweep]
metric = score
goal = maximize

[sweep.train.total_timesteps]
distribution = uniform
min = 5e7
max = 9e8
mean = 5e8
scale = auto

[sweep.env.work_tape_size]
distribution = uniform
min = 50
max = 120
mean = 100
scale = auto

[sweep.env.state_tape_size]
distribution = uniform
min = 50
max = 120
mean = 100
scale = auto

[sweep.env.result_tape_size]
distribution = uniform
min = 50
max = 120
mean = 100
scale = auto

[sweep.env.work_observation_window]
distribution = uniform
min = 10
max = 30
mean = 20
scale = auto

[sweep.env.state_observation_window]
distribution = uniform
min = 10
max = 30
mean = 20
scale = auto

[sweep.env.result_observation_window]
distribution = uniform
min = 10
max = 30
mean = 20
scale = auto

; [sweep.env.tape_alphabet]
; distribution = uniform
; min = 5
; max = 20
; mean = 10
; scale = auto

[sweep.env.move_head]
distribution = uniform
min = 5
max = 40
mean = 23
scale = auto

[sweep.env.num_work_heads]
distribution = uniform
min = 1
max = 3
mean = 2
scale = auto

; [sweep.env.num_state_heads]
; distribution = uniform
; min = 1
; max = 3
; mean = 2
; scale = auto

; [sweep.env.num_result_heads]
; distribution = uniform
; min = 1
; max = 3
; mean = 2
; scale = auto

[sweep.env.nen_halt_penalty]
distribution = uniform
min = 0.1
max = 1.0
mean = 0.5
scale = auto

[sweep.env.invalid_output_penalty]
distribution = uniform
min = 1.0
max = 5.0
mean = 3.0
scale = auto

[sweep.env.cont_rew_mul]
distribution = uniform
min = 10.0
max = 20.0
mean = 15.0
scale = auto

[sweep.env.cont_rew_div]
distribution = uniform
min = 0.1
max = 3.0
mean = 1.0
scale = auto

[sweep.env.write_rew_multiplier]
distribution = uniform
min = 6
max = 15.0
mean = 10.0
scale = auto

[sweep.env.correctness_reward]
distribution = uniform
min = 20.0
max = 60.0
mean = 40.0
scale = auto

[sweep.env.incorrectness_penalty]
distribution = uniform
min = 0.0
max = 50.0
mean = 25.0
scale = auto

[sweep.env.max_steps]
distribution = uniform
min = 100
max = 1000
mean = 550
scale = auto

; [sweep.env.problem_size]
; distribution = uniform
; min = 3
; max = 5
; mean = 4
; scale = auto
