[base]
package = ocean
env_name = puffer_table_ocr
policy_name = TableOCR
rnn_name = TableOCRLSTM

[vec]
num_envs = 6

[env]
num_envs = 1024
img_height = 2310
img_width = 1784
n_cell_boxes = 37
d_position = 20
log_interval = 100
log_episodes = 10
min_steps = 6
max_steps = 170
stable_r_coeff = 0.01
epsilon_cell = 0
epsilon_del = 2


[train]
total_timesteps = 150_000_000
gamma = 0.999
learning_rate = 0.01
minibatch_size = 32768
checkpoint_interval = 10

[sweep]
metric = n_clustered
goal = maximize

[sweep.env.min_steps]
distribution = uniform
min = 2
max = 10
mean = 6
scale = auto

[sweep.env.max_steps]
distribution = uniform
min = 20
max = 500
mean = 170
scale = auto

[sweep.env.stable_r_coeff]
distribution = uniform
min = 0.0
max = 0.5
mean = 0.1
scale = auto

[sweep.env.d_position]
distribution = uniform
min = 7.0
max = 30.0
mean = 14.0
scale = auto

[sweep.train.total_timesteps]
distribution = uniform
min = 50_000_000
max = 400_000_000
mean = 200_000_000
scale = auto

; [sweep.env.epsilon_cell]
; distribution = uniform
; min = 1
; max = 5
; mean = 3
; scale = auto

[sweep.env.epsilon_del]
distribution = uniform
min = 1
max = 4
mean = 2
scale = auto