[base]
package = ocean
env_name = puffer_table_transformer
policy_name = TableTransformer
rnn_name = TableTransformerLSTM

[vec]
num_envs = 6
num_workers = 6

[env]
num_envs = 768
img_height = 7015
img_width = 4962
n_cell_boxes = 46
r_text_const_1 = 1
step_penalty = 0.01
d_position = 20
log_interval = 100
min_steps = 6
max_steps = 170
stable_r_coeff = 0.01
done_r_coeff = 10
doesnt_del_before = 90
max_deletes = 20
epsilon_cell = 0.1


[train]
total_timesteps = 150_000_000
gamma = 0.999
learning_rate = 0.01
minibatch_size = 4608
checkpoint_interval = 10

[sweep.env.min_steps]
distribution = uniform
min = 2
max = 10
mean = 6
scale = auto

[sweep.env.max_steps]
distribution = uniform
min = 20
max = 500
mean = 170
scale = auto

; [sweep.env.stable_r_coeff]
; distribution = uniform
; min = 0.0
; max = 0.5
; mean = 0.1
; scale = auto

[sweep.env.done_r_coeff]
distribution = uniform
min = 1.0
max = 3.0
mean = 2.0
scale = auto

[sweep.env.d_position]
distribution = uniform
min = 15.0
max = 30.0
mean = 20.0
scale = auto

; [sweep.env.step_penalty]
; distribution = uniform
; min = 0.0
; max = 0.1
; mean = 0.05
; scale = auto

; [sweep.env.r_cut_const_1]
; distribution = uniform
; min = 0.5
; max = 1.5
; mean = 1.0
; scale = auto

; [sweep.env.r_row_const_1]
; distribution = uniform
; min = 250
; max = 500
; mean = 375
; scale = auto

[sweep.env.r_text_const_1]
distribution = uniform
min = 1
max = 10
mean = 5.5
scale = auto


; [sweep.train.total_timesteps]
; distribution = uniform
; min = 50_000_000
; max = 200_000_000
; mean = 100_000_000

[sweep.env.doesnt_del_before]
distribution = uniform
min = 10
max = 50
mean = 30
scale = auto

[sweep.env.max_deletes]
distribution = uniform
min = 15
max = 40
mean = 27
scale = auto

[sweep.env.epsilon_cell]
distribution = uniform
min = 1
max = 20
mean = 10
scale = auto